#!/usr/bin/env bash
set -euo pipefail

export DRY_RUN=false
export FORCE=false
VMARGS=()

for arg in "$@"; do
	case "$arg" in
	--dry-run)
		export DRY_RUN=true
		;;
	--yes)
		export FORCE=true
		;;
	*)
		VMARGS+=("$arg")
		;;
	esac
done

# Load common environment
source "$(dirname "$0")/../lib/_command.sh"

vm_action delete "${VMARGS[@]}"
