#!/usr/bin/env bash
set -euo pipefail

# Load common environment
source "$(dirname "$0")/../lib/_command.sh"

# Execute the command
DRY_RUN=false

ARGS=()

for arg in "$@"; do
	case "$arg" in
		--dry-run)
			DRY_RUN=true
			;;
		*)
			ARGS+=("$arg")
			;;
	esac
done

vm_action delete "${ARGS[@]}"
