#!/usr/bin/env bash
set -euo pipefail

export DRY_RUN=false
VMARGS=()

for arg in "$@"; do
	case "$arg" in
	--dry-run)
		export DRY_RUN=true
		;;
	*)
		VMARGS+=("$arg")
		;;
	esac
done

# Load common environment
source "$(dirname "$0")/../lib/_command.sh"

vm_action shutdown "${VMARGS[@]}"
